# Generated by Django 5.0.4 on 2026-02-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for the image', max_length=200)),
                ('image', models.ImageField(help_text='Upload image', upload_to='events/images/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Optional caption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event obrázok',
                'verbose_name_plural': 'Event obrázky',
                'db_table': 'event_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content_html', models.TextField(help_text='HTML content')),
                ('excerpt', models.TextField(blank=True, help_text='Short description for list view', max_length=500)),
                ('author', models.CharField(blank=True, help_text='Author name', max_length=100)),
                ('datetime', models.DateTimeField(help_text='Event date and time')),
                ('place', models.CharField(help_text='Event location/venue', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Eventy',
                'db_table': 'events',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['is_published', 'datetime'], name='events_is_publ_a631b7_idx'), models.Index(fields=['slug'], name='events_slug_930801_idx')],
            },
        ),
    ]
