# Generated by Django 5.0.4 on 2026-01-24 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterPopupStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', help_text='Session identifier for anonymous users', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email if user subscribed', max_length=254, null=True)),
                ('action', models.CharField(blank=True, choices=[('subscribed', 'Subscribed'), ('dismissed', 'Dismissed/Closed')], default='dismissed', help_text='What the user did with the popup', max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser user agent string')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who interacted (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter Popup Statistic',
                'verbose_name_plural': 'Newsletter Popup Statistics',
                'db_table': 'newsletter_popup_stats',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='newsletter__created_69e859_idx'), models.Index(fields=['action'], name='newsletter__action_89ad9f_idx'), models.Index(fields=['session_id'], name='newsletter__session_e6572a_idx')],
            },
        ),
    ]
