# Generated by Django 5.0.4 on 2026-02-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletterpopupstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Špeciálna zľava len pre vás!', help_text='Email subject line', max_length=200)),
                ('content_html', models.TextField(blank=True, default='', help_text='HTML content for the email')),
                ('preview_text', models.CharField(blank=True, default='', help_text='Preview text shown in email clients', max_length=200)),
                ('discount_code', models.CharField(blank=True, default='', help_text='Actual discount code to include in email', max_length=50)),
                ('discount_percentage', models.IntegerField(blank=True, help_text='Discount percentage (e.g., 10 for 10%)', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='When the discount code expires', null=True)),
                ('last_sent', models.DateTimeField(blank=True, help_text='Last time this template was sent', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discount Code Template (Zľavové kódy)',
                'verbose_name_plural': 'Discount Code Template (Zľavové kódy)',
                'db_table': 'discount_code_template',
            },
        ),
        migrations.CreateModel(
            name='NewsletterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for the image', max_length=200)),
                ('image', models.ImageField(help_text='Upload image for newsletter', upload_to='newsletter/images/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Optional caption or description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Image',
                'verbose_name_plural': 'Newsletter Images',
                'db_table': 'newsletter_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Novinky z nášho obchodu', help_text='Email subject line', max_length=200)),
                ('content_html', models.TextField(blank=True, default='', help_text='HTML content for the email')),
                ('preview_text', models.CharField(blank=True, default='', help_text='Preview text shown in email clients', max_length=200)),
                ('last_sent', models.DateTimeField(blank=True, help_text='Last time this template was sent', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Template (Novinky)',
                'verbose_name_plural': 'Newsletter Template (Novinky)',
                'db_table': 'newsletter_template',
            },
        ),
    ]
