# Generated by Django 5.0.4 on 2026-02-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_discountcodetemplate_newsletterimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcodetemplate',
            name='preview_text',
        ),
        migrations.AlterField(
            model_name='discountcodetemplate',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='HTML šablóna emailu. Dostupné Jinja2 premenné: {{site_url}}, {{unsubscribe_url}}, {{discount_code}}, {{discount_percentage}}, {{valid_until}}, {{email}}'),
        ),
        migrations.AlterField(
            model_name='discountcodetemplate',
            name='discount_code',
            field=models.CharField(blank=True, default='', help_text='Zľavový kód, ktorý sa vloží do emailu', max_length=50),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='HTML šablóna emailu. Dostupné Jinja2 premenné: {{site_url}}, {{unsubscribe_url}}, {{email}}'),
        ),
    ]
