# Generated by Django 5.0.4 on 2026-02-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_remove_discountcodetemplate_preview_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettertemplate',
            name='preview_text',
        ),
    ]
