# Generated by Django 5.0.4 on 2026-02-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_remove_newslettertemplate_preview_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcodetemplate',
            options={'verbose_name': 'Zľavový kód šablóna', 'verbose_name_plural': 'Zľavové kódy šablóny'},
        ),
        migrations.AlterModelOptions(
            name='newsletterimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Obrázok', 'verbose_name_plural': 'Obrázky'},
        ),
        migrations.AlterModelOptions(
            name='newsletterpopupstat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Newsletter Štatistika', 'verbose_name_plural': 'Newsletter Štatistiky'},
        ),
        migrations.AlterModelOptions(
            name='newslettertemplate',
            options={'verbose_name': 'Novinky šablóna', 'verbose_name_plural': 'Novinky šablóny'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Odberateľ', 'verbose_name_plural': 'Odberatelia'},
        ),
        migrations.AlterField(
            model_name='discountcodetemplate',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='HTML šablóna emailu. Dostupné Jinja2 premenné: {{site_url}}, {{unsubscribe_url}}, {{discount_code}}, {{discount_percentage}}, {{valid_until}}, {{email}}. Príklady: <a href="{{site_url}}/produkty">Produkty</a>, <a href="{{unsubscribe_url}}">Odhlásiť sa</a>'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='HTML šablóna emailu. Dostupné Jinja2 premenné: {{site_url}}, {{unsubscribe_url}}, {{email}}. Príklady: <a href="{{site_url}}/produkty">Produkty</a>, <a href="{{unsubscribe_url}}">Odhlásiť sa</a>'),
        ),
    ]
