# Generated by Django 5.0.4 on 2026-02-09 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_alter_discountcode_options_alter_qrcode_options'),
        ('newsletter', '0006_alter_discountcodetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcodetemplate',
            name='selected_discount_code',
            field=models.ForeignKey(blank=True, help_text='Vyberte existujúci zľavový kód', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_templates', to='loyalty.discountcode'),
        ),
        migrations.AlterField(
            model_name='discountcodetemplate',
            name='discount_code',
            field=models.CharField(blank=True, default='', help_text='Zľavový kód (vyplní sa automaticky)', max_length=50),
        ),
        migrations.AlterField(
            model_name='discountcodetemplate',
            name='discount_percentage',
            field=models.IntegerField(blank=True, help_text='Discount percentage (vyplní sa automaticky)', null=True),
        ),
    ]
