# Generated by Django 5.0.4 on 2026-02-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_discountcodetemplate_selected_discount_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterpopupstat',
            name='action',
            field=models.CharField(blank=True, choices=[('shown', 'Popup Shown'), ('subscribed', 'Subscribed'), ('dismissed', 'Dismissed/Closed')], default='dismissed', help_text='What the user did with the popup', max_length=20, null=True),
        ),
    ]
