# Generated by Django 5.0.4 on 2026-02-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_alter_newsletterpopupstat_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletterpopupstat',
            options={'verbose_name': 'Newsletter Popup Štatistika', 'verbose_name_plural': 'Newsletter Popup Štatistiky'},
        ),
        migrations.RemoveIndex(
            model_name='newsletterpopupstat',
            name='newsletter__created_69e859_idx',
        ),
        migrations.RemoveIndex(
            model_name='newsletterpopupstat',
            name='newsletter__action_89ad9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='newsletterpopupstat',
            name='newsletter__session_e6572a_idx',
        ),
        migrations.RemoveField(
            model_name='newsletterpopupstat',
            name='action',
        ),
        migrations.RemoveField(
            model_name='newsletterpopupstat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newsletterpopupstat',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newsletterpopupstat',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='newsletterpopupstat',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='newsletterpopupstat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newsletterpopupstat',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='newsletterpopupstat',
            name='dismissed_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times popup was dismissed/closed'),
        ),
        migrations.AddField(
            model_name='newsletterpopupstat',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsletterpopupstat',
            name='shown_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times popup was shown'),
        ),
        migrations.AddField(
            model_name='newsletterpopupstat',
            name='subscribed_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times users subscribed via popup'),
        ),
    ]
