# Generated by Django 5.0.4 on 2026-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_alter_newsletterpopupstat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Nové blogy na webe!', help_text='Email subject line', max_length=200)),
                ('content_html', models.TextField(blank=True, default='', help_text='HTML šablóna emailu. Dostupné Jinja2 premenné: {{site_url}}, {{unsubscribe_url}}, {{email}}.')),
                ('last_sent', models.DateTimeField(blank=True, help_text='Last time this template was sent', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blogy šablóna',
                'verbose_name_plural': 'Blogy šablóny',
                'db_table': 'blogs_newsletter_template',
            },
        ),
        migrations.CreateModel(
            name='EventsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Nadchádzajúce eventy pre vás!', help_text='Email subject line', max_length=200)),
                ('content_html', models.TextField(blank=True, default='', help_text='HTML šablóna emailu. Dostupné Jinja2 premenné: {{site_url}}, {{unsubscribe_url}}, {{email}}.')),
                ('last_sent', models.DateTimeField(blank=True, help_text='Last time this template was sent', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eventy šablóna',
                'verbose_name_plural': 'Eventy šablóny',
                'db_table': 'events_newsletter_template',
            },
        ),
    ]
