# Generated by Django 5.0.4 on 2026-01-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='max_uses',
            field=models.IntegerField(default=1, help_text='Maximum number of times this code can be used'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order value to apply discount (e.g., 50.00 for 50€)', max_digits=10),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Number of times this code has been used'),
        ),
    ]
