# Generated by Django 5.0.4 on 2026-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_discountcode_max_uses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='max_uses',
            field=models.IntegerField(blank=True, help_text='Maximum number of times this code can be used (leave empty for unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Expiration date (leave empty for no expiration)', null=True),
        ),
    ]
