# Generated by Django 5.0.4 on 2026-01-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_alter_discountcode_max_uses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code_type',
            field=models.CharField(choices=[('loyalty', 'Loyalty Reward'), ('promotion', 'Promotion'), ('referral', 'Referral'), ('newsletter', 'Newsletter Signup')], default='loyalty', max_length=20),
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for this QR code', max_length=200)),
                ('code', models.CharField(help_text='Unique identifier for the QR code', max_length=50, unique=True)),
                ('qr_type', models.CharField(choices=[('product', 'Product Link'), ('discount', 'Discount Code'), ('website', 'Website URL'), ('social', 'Social Media'), ('other', 'Other')], default='other', help_text='Type of QR code', max_length=20)),
                ('target_url', models.URLField(help_text='Target URL when QR code is scanned', max_length=500)),
                ('scan_count', models.IntegerField(default=0, help_text='Number of times this QR code has been scanned')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this QR code is active')),
                ('description', models.TextField(blank=True, help_text='Additional notes or description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, help_text='Last time this QR code was scanned', null=True)),
                ('discount_code', models.ForeignKey(blank=True, help_text='Associated discount code (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='loyalty.discountcode')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'db_table': 'qr_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='qr_codes_code_61971c_idx'), models.Index(fields=['is_active'], name='qr_codes_is_acti_b3a3a3_idx'), models.Index(fields=['-scan_count'], name='qr_codes_scan_co_c42874_idx')],
            },
        ),
    ]
