# Generated by Django 5.0.4 on 2026-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_alter_discountcode_code_type_qrcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Zľavový kód', 'verbose_name_plural': 'Zľavové kódy'},
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'QR kód', 'verbose_name_plural': 'QR kódy'},
        ),
    ]
