# Generated by Django 5.0.4 on 2026-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_alter_discountcode_options_alter_qrcode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='is_free_shipping',
            field=models.BooleanField(default=False, help_text='If True, this code provides free shipping regardless of order value'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (e.g., 10.00 for 10%, can be 0 for free shipping only)', max_digits=5),
        ),
    ]
