# Generated by Django 5.0.4 on 2026-01-15 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price in EUR (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='is_limited_drop',
            field=models.BooleanField(default=False, help_text='Limited edition drop (1/1 unique pieces)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recycled',
            field=models.BooleanField(default=False, help_text='Made from recycled materials'),
        ),
    ]
