# Generated by Django 5.0.4 on 2026-01-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_discount_price_product_is_limited_drop_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Product Video', 'verbose_name_plural': 'Product Videos'},
        ),
        migrations.AddField(
            model_name='productvideo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='shop.product'),
        ),
    ]
