# Generated by Django 5.0.4 on 2026-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productvideo_options_productvideo_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategória', 'verbose_name_plural': 'Kategórie'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'Farba', 'verbose_name_plural': 'Farby'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Obrázok produktu', 'verbose_name_plural': 'Obrázky produktov'},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Video produktu', 'verbose_name_plural': 'Videá produktov'},
        ),
    ]
