# Generated by Django 5.0.4 on 2026-02-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='en_name',
            field=models.CharField(blank=True, default='', help_text='English name', max_length=100),
        ),
        migrations.AddField(
            model_name='color',
            name='en_name',
            field=models.CharField(blank=True, default='', help_text='English name', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='en_description',
            field=models.TextField(blank=True, default='', help_text='English description'),
        ),
        migrations.AddField(
            model_name='product',
            name='en_name',
            field=models.CharField(blank=True, default='', help_text='English name', max_length=200),
        ),
    ]
