# Generated by Django 5.0.4 on 2026-02-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_en_name_color_en_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_limited_drop'], name='products_is_limi_3f8114_idx'),
        ),
    ]
