# Generated by Django 5.0.4 on 2026-03-17 17:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_products_is_limi_3f8114_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.color'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('en_name', models.CharField(blank=True, default='', help_text='English name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Ticket / event description')),
                ('en_description', models.TextField(blank=True, default='', help_text='English description')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price in EUR (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('event_date', models.DateTimeField(blank=True, help_text='Date and time of the event', null=True)),
                ('event_location', models.CharField(blank=True, help_text='Event location / venue', max_length=300)),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='Total available tickets (0 = unlimited)')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vstupenka',
                'verbose_name_plural': 'Vstupenky',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='tickets_slug_76fc3c_idx'), models.Index(fields=['is_published'], name='tickets_is_publ_539cbb_idx')],
            },
        ),
    ]
