# Generated by Django 5.0.4 on 2026-03-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_color_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tickets/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.ticket')),
            ],
            options={
                'verbose_name': 'Obrázok vstupenky',
                'verbose_name_plural': 'Obrázky vstupeniek',
                'db_table': 'ticket_images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
