# Generated by Django 5.0.4 on 2026-01-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_password_reset_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('regular', 'Regular User'), ('staff', 'Staff')], default='regular', help_text='User role (for non-superusers)', max_length=20),
        ),
    ]
