# Generated by Django 5.0.4 on 2026-04-24 15:08

from django.db import migrations, models


def sync_backoffice_staff_flags(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(is_superuser=True).update(is_staff=True)
    User.objects.filter(user_role__in=['staff', 'seller']).update(is_staff=True)
    User.objects.filter(is_superuser=False, user_role='regular').update(is_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('regular', 'Regular User'), ('staff', 'Staff'), ('seller', 'Seller')], default='regular', help_text='User role (for non-superusers)', max_length=20),
        ),
        migrations.RunPython(sync_backoffice_staff_flags, migrations.RunPython.noop),
    ]
