# Generated by Django 5.0.4 on 2026-01-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('gopay', 'GoPay Online Payment'), ('cash_on_pickup', 'Cash on Personal Pickup')], default='gopay', help_text='Payment method chosen by customer', max_length=20),
        ),
    ]
