# Generated by Django 5.0.4 on 2026-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Platobná transakcia', 'verbose_name_plural': 'Platobné transakcie'},
        ),
    ]
