# Generated by Django 5.0.4 on 2026-01-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum cart value for free shipping (EUR)', max_digits=10)),
                ('standard_shipping_cost', models.DecimalField(decimal_places=2, default=5.99, help_text='Standard shipping cost (EUR)', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Tax rate percentage (e.g., 20 for 20%)', max_digits=5)),
                ('site_name', models.CharField(default='Wake TF Up', help_text='Site name displayed in emails and frontend', max_length=200)),
                ('contact_email', models.EmailField(default='info@waketfup.com', help_text='Main contact email', max_length=254)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('max_cart_quantity', models.PositiveIntegerField(default=10, help_text='Maximum quantity per product in cart')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (show maintenance page)')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to display during maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Main Settings',
                'verbose_name_plural': 'Main Settings',
                'db_table': 'main_settings',
            },
        ),
    ]
