# Generated by Django 5.0.4 on 2026-01-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='dpd_courier_cost',
            field=models.DecimalField(decimal_places=2, default=5.99, help_text='DPD courier delivery cost (EUR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='packeta_box_cost',
            field=models.DecimalField(decimal_places=2, default=3.99, help_text='Packeta box (Z-BOX) delivery cost (EUR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='packeta_courier_cost',
            field=models.DecimalField(decimal_places=2, default=4.99, help_text='Packeta courier delivery cost (EUR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='pickup_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Personal pickup cost (EUR) - usually 0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='standard_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=5.99, help_text='Standard shipping cost (EUR) - DEPRECATED', max_digits=10),
        ),
    ]
