# Generated by Django 5.0.4 on 2026-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_mainsettings_dpd_courier_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='newsletter_popup_delay',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Minutes before showing newsletter popup (default: 5)', null=True),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='newsletter_popup_enabled',
            field=models.BooleanField(blank=True, default=True, help_text='Enable automatic newsletter popup', null=True),
        ),
    ]
