# Generated by Django 5.0.4 on 2026-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_mainsettings_newsletter_popup_delay_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainsettings',
            options={'verbose_name': 'Hlavné nastavenia', 'verbose_name_plural': 'Hlavné nastavenia'},
        ),
    ]
