# Generated by Django 5.0.4 on 2026-02-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_mainsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='contact_email',
            field=models.EmailField(default='info@wake-tf-up.com', help_text='Main contact email', max_length=254),
        ),
    ]
