# Generated by Django 5.0.4 on 2026-02-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_mainsettings_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='address',
            field=models.CharField(default='Jedľová 319/33, 010 04 Žilina', help_text='Company address', max_length=255),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='country',
            field=models.CharField(default='Slovakia', help_text='Country name', max_length=100),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='phone',
            field=models.CharField(default='+421 917 207 760', help_text='Contact phone number', max_length=20),
        ),
    ]
