# Generated by Django 5.0.4 on 2026-02-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_mainsettings_address_mainsettings_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='company_id',
            field=models.CharField(default='56698585', help_text='Company registration ID (IČO)', max_length=50),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='owner_name',
            field=models.CharField(default='Patrik Bielčik', help_text='Owner/Operator name', max_length=200),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='tax_id',
            field=models.CharField(default='1127876057', help_text='Tax ID (DIČ)', max_length=50),
        ),
    ]
