# Generated by Django 5.0.4 on 2026-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_mainsettings_company_id_mainsettings_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='review_email_days_after_delivery',
            field=models.PositiveIntegerField(default=7, help_text='Number of days after delivery to send review request email (default: 7)'),
        ),
    ]
