# Generated by Django 5.0.4 on 2026-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_mainsettings_review_email_days_after_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='orders_email',
            field=models.EmailField(default='orders@wake-tf-up.eu', help_text='Orders contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='tiktok_url',
            field=models.URLField(blank=True, default='https://www.tiktok.com/@waketfup_eu', help_text='TikTok profile URL'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='contact_email',
            field=models.EmailField(default='info@wake-tf-up.eu', help_text='Main contact email', max_length=254),
        ),
    ]
