# Generated by Django 5.0.4 on 2026-02-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_mainsettings_orders_email_mainsettings_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='newsletter_popup_delay',
            field=models.PositiveIntegerField(blank=True, default=300, help_text='Seconds before showing newsletter popup (default: 300)', null=True),
        ),
    ]
