# Generated by Django 5.0.4 on 2026-04-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_mainsettings_newsletter_popup_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='digital_delivery_enabled',
            field=models.BooleanField(default=True, help_text='Enable digital delivery in checkout'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='dpd_courier_enabled',
            field=models.BooleanField(default=True, help_text='Enable DPD courier delivery in checkout'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='packeta_box_enabled',
            field=models.BooleanField(default=True, help_text='Enable Packeta Z-Box delivery in checkout'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='packeta_courier_enabled',
            field=models.BooleanField(default=True, help_text='Enable Packeta courier delivery in checkout'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='pickup_enabled',
            field=models.BooleanField(default=True, help_text='Enable personal pickup in checkout'),
        ),
    ]
