# Generated by Django 5.0.4 on 2026-01-24 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_discount_amount_order_discount_code'),
        ('reviews', '0001_initial'),
        ('shop', '0003_alter_productvideo_options_productvideo_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tokens', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tokens', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Token',
                'verbose_name_plural': 'Review Tokens',
                'db_table': 'review_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_used'], name='review_toke_token_55ca0d_idx'), models.Index(fields=['expires_at'], name='review_toke_expires_65341d_idx')],
                'unique_together': {('order', 'product')},
            },
        ),
    ]
