# Generated by Django 5.0.4 on 2026-01-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='If true, reviewer name will not be shown'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, default='', help_text='Name to display with review (optional)', max_length=100),
        ),
    ]
