# Generated by Django 5.0.4 on 2026-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_is_anonymous_review_reviewer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recenzia', 'verbose_name_plural': 'Recenzie'},
        ),
        migrations.AlterModelOptions(
            name='reviewtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token recenzie', 'verbose_name_plural': 'Tokeny recenzii'},
        ),
    ]
