# Generated by Django 5.0.4 on 2026-01-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_company',
            field=models.CharField(blank=True, help_text='Company name', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_dic',
            field=models.CharField(blank=True, help_text='DIČ (Tax ID)', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_ic_dph',
            field=models.CharField(blank=True, help_text='IČ DPH (VAT ID)', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_ico',
            field=models.CharField(blank=True, help_text='IČO (Company ID)', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='is_company_purchase',
            field=models.BooleanField(default=False, help_text='Is this a company purchase?'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'Personal Pickup'), ('packeta', 'Packeta Z-Box'), ('courier', 'Courier')], default='courier', help_text='Delivery method selected by customer', max_length=20),
        ),
    ]
