# Generated by Django 5.0.4 on 2026-01-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_tracking_url',
            field=models.URLField(blank=True, help_text='URL to track shipment'),
        ),
        migrations.AddField(
            model_name='order',
            name='packeta_packet_id',
            field=models.CharField(blank=True, help_text='Packeta internal packet ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='packeta_point_address',
            field=models.TextField(blank=True, help_text='Packeta pickup point address'),
        ),
        migrations.AddField(
            model_name='order',
            name='packeta_point_id',
            field=models.CharField(blank=True, help_text='Packeta pickup point ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='packeta_point_name',
            field=models.CharField(blank=True, help_text='Packeta pickup point name', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Carrier tracking number', max_length=100),
        ),
    ]
