# Generated by Django 5.0.4 on 2026-01-20 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_discountcode_max_uses_and_more'),
        ('orders', '0004_order_carrier_tracking_url_order_packeta_packet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, help_text='Applied discount code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='loyalty.discountcode'),
        ),
    ]
