# Generated by Django 5.0.4 on 2026-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('gopay', 'GoPay Online Payment'), ('cash_on_pickup', 'Cash on Personal Pickup')], default='gopay', help_text='Payment method selected at checkout', max_length=20),
        ),
    ]
