# Generated by Django 5.0.4 on 2026-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost (EUR)', max_digits=10),
        ),
    ]
