# Generated by Django 5.0.4 on 2026-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when order was marked as delivered', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_request_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when review request email was sent', null=True),
        ),
    ]
