# Generated by Django 5.0.4 on 2026-02-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivered_at_order_review_request_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(choices=[('sk', 'Slovak'), ('en', 'English')], default='sk', help_text='Language preference for emails and communications', max_length=2),
        ),
    ]
