# Generated by Django 5.0.4 on 2026-03-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_language'),
        ('shop', '0007_alter_product_color_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.ticket'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product'),
        ),
        migrations.CreateModel(
            name='PurchasedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique 8-character access code', max_length=8, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by_note', models.CharField(blank=True, help_text='Optional note when marking as used', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_tickets', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_tickets', to='orders.orderitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_tickets', to='shop.ticket')),
            ],
            options={
                'verbose_name': 'Kúpená vstupenka',
                'verbose_name_plural': 'Kúpené vstupenky',
                'db_table': 'purchased_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
