# Generated by Django 5.0.4 on 2026-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_ticket_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'Personal Pickup'), ('dpd_courier', 'DPD Courier'), ('packeta_box', 'Packeta Z-Box'), ('packeta_courier', 'Packeta Courier'), ('digital_delivery', 'Digital Delivery')], default='dpd_courier', help_text='Delivery method selected by customer', max_length=20),
        ),
    ]
