# Generated by Django 5.0.4 on 2026-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content_html', models.TextField(help_text='HTML content')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', 'created_at'], name='blog_posts_is_publ_5269f5_idx'), models.Index(fields=['slug'], name='blog_posts_slug_b4ca25_idx')],
            },
        ),
    ]
