# Generated by Django 5.0.4 on 2026-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog obrázok', 'verbose_name_plural': 'Blog obrázky'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog článok', 'verbose_name_plural': 'Blog články'},
        ),
    ]
