# Generated by Django 5.0.4 on 2026-01-15 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Anonymous session ID', max_length=100)),
                ('event_type', models.CharField(choices=[('view', 'Product View'), ('click', 'Product Click')], default='view', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shop.product')),
                ('user', models.ForeignKey(blank=True, help_text='Logged in user (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Event',
                'verbose_name_plural': 'Product Events',
                'db_table': 'product_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='product_eve_product_672477_idx'), models.Index(fields=['event_type', 'created_at'], name='product_eve_event_t_e56d09_idx')],
            },
        ),
    ]
