# Generated by Django 5.0.4 on 2026-02-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('shop', '0004_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Udalosť produktu', 'verbose_name_plural': 'Udalosti produktu'},
        ),
        migrations.CreateModel(
            name='ProductEventStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Product View'), ('click', 'Product Click')], default='view', max_length=20)),
                ('count', models.IntegerField(default=0, help_text='Total count of this event type')),
                ('first_recorded_at', models.DateTimeField(auto_now_add=True)),
                ('last_recorded_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_stats', to='shop.product')),
            ],
            options={
                'verbose_name': 'Štatistika udalosti produktu',
                'verbose_name_plural': 'Štatistiky udalostí produktu',
                'db_table': 'product_event_stats',
                'ordering': ['-last_recorded_at'],
                'indexes': [models.Index(fields=['product', 'event_type'], name='product_eve_product_3f4302_idx'), models.Index(fields=['-count'], name='product_eve_count_8a4c70_idx')],
                'unique_together': {('product', 'event_type')},
            },
        ),
    ]
