# Generated by Django 5.0.4 on 2026-02-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_productevent_options_producteventstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productevent',
            name='session_id',
        ),
    ]
